module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        header: "var(--header-bg)",
        headerText: "var(--header-text)",
        sidebar: "var(--sidebar-bg)",
        sidebarText: "var(--sidebar-text)",
        footer: "var(--footer-bg)",
        footerText: "var(--footer-text)",
        btn: "var(--btn-bg)",
        btnText: "var(--btn-text)",
        border: 'var(--border)',
        ring: 'var(--ring)',
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)"
      },
    },
  },
  plugins: [],
};
